name: flutter_otp_auto_field
description: >-
  A complete Flutter OTP plugin that handles Android/iOS OTP autofill,
  retrieves the app signature hash, and offers a fully customizable OTP input field.
version: 1.0.0

homepage: https://github.com/deepak-devflutter/flutter_otp_field
repository: https://github.com/deepak-devflutter/flutter_otp_field
issue_tracker: https://github.com/deepak-devflutter/flutter_otp_field/issues
documentation: https://github.com/deepak-devflutter/flutter_otp_field#readme

environment:
  sdk: ^3.6.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ds.devflutter.flutter_otp_auto_field
        pluginClass: FlutterOtpAutoFieldPlugin
      ios:
        pluginClass: FlutterOtpAutoFieldPlugin
